// @generated by tools/gpio_af/generate_altmap.py from
// af_table_um.tsv (N32L40x UM V2.5.0). DO NOT EDIT BY HAND.
// Every pin entry's AF number is traceable to that table.
//
// N32L40x selects pin AF via per-pin AFL/AFH nibble (STM32 model);
// each pin is gpio::PXn<Alternate<A, Otype>> with concrete A.

use super::*;
use core::marker::PhantomData;
use crate::gpio::NoPin;

pub mod spi1 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Spi1 as PER};

    pin! {
        <Nss> default: PushPull for no:NoPin, [
            PA4: 0,
            PA8: 5,
            PB6: 4,
            PD7: 6,
        ],

        <Sck> default: PushPull for no:NoPin, [
            PA10: 0,
            PA5: 0,
            PB3: 1,
            PD4: 5,
        ],

        <Miso> default: PushPull for no:NoPin, [
            PA0: 0,
            PA6: 0,
            PB4: 1,
            PD5: 5,
        ],

        <Mosi> default: PushPull for no:NoPin, [
            PA7: 0,
            PB5: 0,
            PD6: 5,
        ],

    }

    impl SpiCommon for PER {
        type Sck = Sck;
        type Miso = Miso;
        type Mosi = Mosi;
        type Nss = Nss;
    }
}

pub mod spi2 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Spi2 as PER};

    pin! {
        <Nss> default: PushPull for no:NoPin, [
            PA13: 5,
            PA15: 1,
            PB12: 0,
            PC6: 5,
        ],

        <Sck> default: PushPull for no:NoPin, [
            PA10: 5,
            PB13: 0,
            PB6: 5,
            PC7: 5,
            PD12: 5,
        ],

        <Miso> default: PushPull for no:NoPin, [
            PA11: 0,
            PB14: 0,
            PC8: 5,
        ],

        <Mosi> default: PushPull for no:NoPin, [
            PA12: 0,
            PB15: 0,
            PC9: 5,
        ],

    }

    impl SpiCommon for PER {
        type Sck = Sck;
        type Miso = Miso;
        type Mosi = Mosi;
        type Nss = Nss;
    }
}

pub mod usart1 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Usart1 as PER};

    pin! {
        <Ck> default: PushPull for no:NoPin, [
            PA8: 4,
        ],

        <Cts> default: PushPull for no:NoPin, [
            PA11: 4,
        ],

        <Rts> default: PushPull for no:NoPin, [
            PA12: 4,
        ],

        <Rx> default: PushPull for no:NoPin, [
            PA10: 4,
            PA5: 4,
            PB7: 0,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PA4: 1,
            PA9: 4,
            PB6: 0,
            PB8: 0,
        ],

    }

    impl SerialAsync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
    }
    impl SerialSync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Ck = Ck;
    }
    impl SerialRs232 for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Cts = Cts;
        type Rts = Rts;
    }
}

pub mod usart2 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Usart2 as PER};

    pin! {
        <Ck> default: PushPull for no:NoPin, [
            PA14: 4,
            PA4: 4,
        ],

        <Cts> default: PushPull for no:NoPin, [
            PA0: 4,
            PA15: 6,
            PD3: 0,
        ],

        <Rts> default: PushPull for no:NoPin, [
            PA1: 4,
            PB3: 4,
        ],

        <Rx> default: PushPull for no:NoPin, [
            PA3: 4,
            PB5: 6,
            PD15: 4,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PA2: 4,
            PB4: 4,
            PD14: 4,
        ],

    }

    impl SerialAsync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
    }
    impl SerialSync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Ck = Ck;
    }
    impl SerialRs232 for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Cts = Cts;
        type Rts = Rts;
    }
}

pub mod usart3 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Usart3 as PER};

    pin! {
        <Ck> default: PushPull for no:NoPin, [
            PB12: 4,
            PC12: 5,
        ],

        <Cts> default: PushPull for no:NoPin, [
            PB13: 7,
        ],

        <Rts> default: PushPull for no:NoPin, [
            PB14: 7,
        ],

        <Rx> default: PushPull for no:NoPin, [
            PB11: 5,
            PC11: 5,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PB10: 0,
            PC10: 5,
        ],

    }

    impl SerialAsync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
    }
    impl SerialSync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Ck = Ck;
    }
    impl SerialRs232 for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Cts = Cts;
        type Rts = Rts;
    }
}

pub mod uart4 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Uart4 as PER};

    pin! {
        <Rx> default: PushPull for no:NoPin, [
            PB1: 6,
            PB15: 6,
            PC11: 6,
            PD12: 6,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PB0: 6,
            PB14: 6,
            PC10: 6,
            PD13: 6,
        ],

    }

    impl SerialAsync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
    }
}

pub mod uart5 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Uart5 as PER};

    pin! {
        <Rx> default: PushPull for no:NoPin, [
            PB5: 7,
            PB9: 6,
            PD2: 6,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PB4: 6,
            PB8: 6,
            PC12: 6,
        ],

    }

    impl SerialAsync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
    }
}

pub mod lpuart {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Lpuart as PER};

    pin! {
        <Cts> default: PushPull for no:NoPin, [
            PB13: 4,
        ],

        <Rts> default: PushPull for no:NoPin, [
            PB1: 7,
            PB12: 2,
            PB14: 4,
            PD2: 0,
        ],

        <Rx> default: PushPull for no:NoPin, [
            PA0: 6,
            PA3: 6,
            PA4: 6,
            PA6: 4,
            PB10: 4,
            PB11: 4,
            PB6: 6,
            PB7: 6,
            PC10: 0,
            PC11: 0,
            PC4: 2,
            PC5: 2,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PA1: 6,
        ],

    }

    impl SerialAsync for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
    }
    impl SerialRs232 for PER {
        type Rx<Itype> = Rx<Input<Itype>>;
        type Tx<Otype> = Tx<Otype>;
        type Cts = Cts;
        type Rts = Rts;
    }
}

pub mod tim1 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim1 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PA8: 2,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PA9: 2,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PA10: 2,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PA11: 2,
        ],

        <Ch1n> default: PushPull for no:NoPin, [
            PA7: 5,
            PB13: 2,
            PC13: 2,
        ],

        <Ch2n> default: PushPull for no:NoPin, [
            PB0: 5,
            PB14: 2,
            PB6: 7,
        ],

        <Ch3n> default: PushPull for no:NoPin, [
            PB1: 5,
            PB15: 2,
            PD14: 2,
        ],

        <Etr> default: PushPull for no:NoPin, [
            PA12: 2,
        ],

        <Bkin> default: PushPull for no:NoPin, [
            PA6: 5,
            PB12: 5,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
    impl TimNCPin<0> for PER {
        type ChN<Otype> = Ch1n<Otype>;
    }
    impl TimNCPin<1> for PER {
        type ChN<Otype> = Ch2n<Otype>;
    }
    impl TimNCPin<2> for PER {
        type ChN<Otype> = Ch3n<Otype>;
    }
    impl TimBkin for PER {
        type Bkin = Bkin;
    }
    impl TimEtr for PER {
        type Etr = Etr;
    }
}

pub mod tim2 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim2 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PA0: 2,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PA1: 2,
            PA15: 5,
            PA2: 2,
            PB3: 2,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PB10: 2,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PB11: 2,
        ],

        <Etr> default: PushPull for no:NoPin, [
            PA0: 5,
            PA15: 2,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
    impl TimEtr for PER {
        type Etr = Etr;
    }
}

pub mod tim3 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim3 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PA6: 2,
            PB4: 2,
            PC6: 2,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PA7: 2,
            PB5: 4,
            PC7: 2,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PB0: 2,
            PC8: 2,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PB1: 2,
            PC9: 2,
        ],

        <Etr> default: PushPull for no:NoPin, [
            PD2: 2,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
    impl TimEtr for PER {
        type Etr = Etr;
    }
}

pub mod tim4 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim4 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PB6: 2,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PB7: 2,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PB8: 2,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PB9: 2,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
}

pub mod tim5 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim5 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PA0: 1,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PA1: 7,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PA2: 6,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PA3: 7,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
}

pub mod tim8 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim8 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PC6: 6,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PC7: 6,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PC8: 6,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PC9: 6,
        ],

        <Ch1n> default: PushPull for no:NoPin, [
            PA7: 6,
        ],

        <Ch2n> default: PushPull for no:NoPin, [
            PB0: 7,
        ],

        <Ch3n> default: PushPull for no:NoPin, [
            PB1: 0,
        ],

        <Etr> default: PushPull for no:NoPin, [
            PA0: 7,
        ],

        <Bkin> default: PushPull for no:NoPin, [
            PA6: 6,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
    impl TimNCPin<0> for PER {
        type ChN<Otype> = Ch1n<Otype>;
    }
    impl TimNCPin<1> for PER {
        type ChN<Otype> = Ch2n<Otype>;
    }
    impl TimNCPin<2> for PER {
        type ChN<Otype> = Ch3n<Otype>;
    }
    impl TimBkin for PER {
        type Bkin = Bkin;
    }
    impl TimEtr for PER {
        type Etr = Etr;
    }
}

pub mod tim9 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Tim9 as PER};

    pin! {
        <Ch1> default: PushPull for no:NoPin, [
            PB12: 1,
        ],

        <Ch2> default: PushPull for no:NoPin, [
            PB13: 1,
        ],

        <Ch3> default: PushPull for no:NoPin, [
            PB14: 1,
        ],

        <Ch4> default: PushPull for no:NoPin, [
            PB15: 1,
        ],

        <Etr> default: PushPull for no:NoPin, [
            PB2: 1,
        ],

    }

    impl TimCPin<0> for PER {
        type Ch<Otype> = Ch1<Otype>;
    }
    impl TimCPin<1> for PER {
        type Ch<Otype> = Ch2<Otype>;
    }
    impl TimCPin<2> for PER {
        type Ch<Otype> = Ch3<Otype>;
    }
    impl TimCPin<3> for PER {
        type Ch<Otype> = Ch4<Otype>;
    }
    impl TimEtr for PER {
        type Etr = Etr;
    }
}

pub mod lptim {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Lptim as PER};

    pin! {
        <In1> default: PushPull for no:NoPin, [
            PB5: 2,
            PC0: 0,
        ],

        <In2> default: PushPull for no:NoPin, [
            PB7: 5,
            PC2: 2,
        ],

        <Out> default: PushPull for no:NoPin, [
            PB2: 2,
            PC1: 0,
        ],

        <Etr> default: PushPull for no:NoPin, [
            PB6: 8,
            PC3: 0,
        ],

    }

}

pub mod i2c1 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::I2c1 as PER};

    pin! {
        <Scl> default: OpenDrain for no:NoPin, [
            PA15: 7,
            PA4: 7,
            PB6: 1,
            PB8: 4,
            PC0: 7,
            PC4: 7,
            PD13: 7,
        ],

        <Sda> default: OpenDrain for no:NoPin, [
            PA14: 7,
            PA5: 7,
            PB7: 1,
            PB9: 4,
            PC1: 7,
            PC5: 7,
            PD12: 7,
        ],

        <Smba> default: PushPull for no:NoPin, [
            PB5: 1,
        ],

    }

    impl I2cCommon for PER {
        type Scl = Scl;
        type Sda = Sda;
        type Smba = Smba;
    }
}

pub mod i2c2 {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::I2c2 as PER};

    pin! {
        <Scl> default: OpenDrain for no:NoPin, [
            PA2: 5,
            PA3: 5,
            PA9: 6,
            PB10: 6,
            PB13: 5,
            PD15: 6,
        ],

        <Sda> default: OpenDrain for no:NoPin, [
            PA10: 6,
            PA8: 6,
            PB11: 6,
            PB14: 5,
        ],

        <Smba> default: PushPull for no:NoPin, [
            PA8: 1,
            PB12: 8,
            PD14: 6,
        ],

    }

    impl I2cCommon for PER {
        type Scl = Scl;
        type Sda = Sda;
        type Smba = Smba;
    }
}

pub mod can {
    use super::*;
    use crate::gpio::{self, Input, PushPull, OpenDrain};
    use crate::{gpio::alt::altmap::pin, pac::Can as PER};

    pin! {
        <Rx> default: PushPull for no:NoPin, [
            PA11: 1,
            PB8: 5,
        ],

        <Tx> default: PushPull for no:NoPin, [
            PA12: 1,
            PB9: 5,
        ],

    }

    impl CanCommon for PER {
        type Rx = Rx;
        type Tx = Tx;
    }
}

